{
  "openapi": "3.1.0",
  "info": {
    "title": "Toggl API",
    "description": "Public Toggl API.\nNote:\nWe use BasicAuth in a specific way. By the standard you provide `Authentication` header with `base64(user_name:password)` as a `credential`.\nIn our case it will be `base64(user_name:api_token)`.",
    "termsOfService": "https://toggl.com/terms/",
    "license": {
      "name": "Toggl Proprietary License"
    },
    "version": "9"
  },
  "servers": [
    {
      "url": "https://api.track.toggl.com/api/v9"
    }
  ],
  "paths": {
    "/me": {
      "parameters": [
        {
          "$ref": "#/components/parameters/with_related_data"
        }
      ],
      "get": {
        "tags": [
          "me"
        ],
        "summary": "Return Current User",
        "description": "Returns details for the current user.",
        "operationId": "GetMe",
        "responses": {
          "200": {
            "$ref": "#/components/responses/UserResponse"
          },
          "401": {
            "$ref": "#/components/responses/UnauthorizedResponse"
          }
        }
      }
    },
    "/workspaces/{workspace_id}/time_entries": {
      "parameters": [
        {
          "$ref": "#/components/parameters/workspace_id"
        }
      ],
      "post": {
        "tags": [
          "time_entries"
        ],
        "summary": "Create a time entry",
        "description": "Creates a new workspace TimeEntry.",
        "operationId": "CreateTimeEntry",
        "requestBody": {
          "$ref": "#/components/requestBodies/TimeEntry"
        },
        "responses": {
          "400": {
            "$ref": "#/components/responses/PostWorkspaces2230580TimeEntriesBadRequestResponse"
          }
        }
      }
    },
    "/me/time_entries/current": {
      "get": {
        "tags": [
          "time_entries"
        ],
        "summary": "Get current time entry",
        "description": "Load running time entry for the current user.",
        "operationId": "GetCurrentTimeEntry",
        "responses": {
          "200": {
            "$ref": "#/components/responses/TimeEntryResponse"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "UserWithRelated": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 2166261
          },
          "api_token": {
            "type": "string",
            "example": "********************************"
          },
          "email": {
            "type": "string",
            "format": "email",
            "example": "marcodroesler@gmail.com"
          },
          "fullname": {
            "type": "string",
            "example": "Marco"
          },
          "timezone": {
            "type": "string",
            "example": "Europe/Berlin"
          },
          "toggl_accounts_id": {
            "type": "string",
            "example": "WSBrE7LiQPJ7PKA7WnCAnk"
          },
          "default_workspace_id": {
            "type": "integer",
            "example": 2230580
          },
          "beginning_of_week": {
            "type": "integer",
            "example": 1
          },
          "image_url": {
            "type": "string",
            "format": "uri",
            "example": "https://secure.gravatar.com/avatar/af0a4ad100669ddbc678eb40ba90459d?d=404&s=200"
          },
          "created_at": {
            "type": "string",
            "format": "date-time",
            "example": "2016-03-20T20:40:08.017845Z"
          },
          "updated_at": {
            "type": "string",
            "format": "date-time",
            "example": "2024-11-26T17:13:54.850204Z"
          },
          "openid_email": {
            "type": "object"
          },
          "openid_enabled": {
            "type": "boolean",
            "example": true
          },
          "country_id": {
            "type": "integer"
          },
          "has_password": {
            "type": "boolean",
            "example": true
          },
          "at": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-11T17:43:57.206072Z"
          },
          "intercom_hash": {
            "type": "string",
            "example": "ea08fc8166eed37e79f7179c3c8334cd99ae5afbbd0339ab1ecb333fb1615d52"
          },
          "oauth_providers": {
            "type": "array",
            "items": {
              "type": "string",
              "example": "google"
            }
          },
          "authorization_updated_at": {
            "description": "A timestamp when the authorization user session object was last updated.",
            "type": "string",
            "format": "date-time",
            "example": "2024-07-02T14:55:08.008327Z"
          },
          "tags": {
            "$ref": "#/components/schemas/Tags"
          },
          "clients": {
            "$ref": "#/components/schemas/Clients",
            "description": "Clients, null if with_related_data was not set to true or if the user does not have any clients"
          },
          "time_entries": {
            "$ref": "#/components/schemas/TimeEntries"
          },
          "options": {
            "$ref": "#/components/schemas/Options"
          },
          "projects": {
            "$ref": "#/components/schemas/Projects",
            "description": "Projects, null if with_related_data was not set to true or if the user does not have any projects"
          },
          "workspaces": {
            "$ref": "#/components/schemas/Workspaces"
          }
        },
        "required": [
          "id",
          "api_token",
          "email",
          "fullname",
          "timezone",
          "toggl_accounts_id",
          "default_workspace_id",
          "beginning_of_week",
          "image_url",
          "created_at",
          "updated_at",
          "openid_email",
          "openid_enabled",
          "country_id",
          "has_password",
          "at",
          "intercom_hash",
          "oauth_providers",
          "authorization_updated_at"
        ],
        "example": {
          "id": 2166261,
          "api_token": "********************************",
          "email": "marcodroesler@gmail.com",
          "fullname": "Marco",
          "timezone": "Europe/Berlin",
          "toggl_accounts_id": "WSBrE7LiQPJ7PKA7WnCAnk",
          "default_workspace_id": 2230580,
          "beginning_of_week": 1,
          "image_url": "https://secure.gravatar.com/avatar/af0a4ad100669ddbc678eb40ba90459d?d=404&s=200",
          "created_at": "2016-03-20T20:40:08.017845Z",
          "updated_at": "2024-11-26T17:13:54.850204Z",
          "openid_email": null,
          "openid_enabled": true,
          "country_id": null,
          "has_password": true,
          "at": "2024-12-11T17:43:57.206072Z",
          "intercom_hash": "ea08fc8166eed37e79f7179c3c8334cd99ae5afbbd0339ab1ecb333fb1615d52",
          "oauth_providers": [
            "google"
          ],
          "authorization_updated_at": "2024-07-02T14:55:08.008327Z"
        }
      },
      "Tags": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Tag"
        }
      },
      "Tag": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 16939168
          },
          "workspace_id": {
            "type": "integer",
            "example": 2230580
          },
          "name": {
            "type": "string",
            "example": "AGL"
          },
          "at": {
            "type": "string",
            "format": "date-time",
            "example": "2024-11-08T19:11:14.332795Z"
          },
          "creator_id": {
            "type": "integer",
            "example": 2166261
          }
        },
        "required": [
          "id",
          "workspace_id",
          "name",
          "at",
          "creator_id"
        ],
        "example": {
          "id": 16939168,
          "workspace_id": 2230580,
          "name": "AGL",
          "at": "2024-11-08T19:11:14.332795Z",
          "creator_id": 2166261
        }
      },
      "Clients": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/WorkClient"
        }
      },
      "WorkClient": {
        "type": "object",
        "properties": {
          "id": {
            "description": "Client ID",
            "type": "integer",
            "example": 64890399
          },
          "wid": {
            "description": "Workspace ID",
            "type": "integer",
            "example": 2230580
          },
          "archived": {
            "description": "true, if the client is archived",
            "type": "boolean",
            "example": false
          },
          "name": {
            "description": "Name of the client",
            "type": "string",
            "example": "AGL"
          },
          "at": {
            "description": "When was the last update",
            "type": "string",
            "format": "date-time",
            "example": "2024-03-17T10:55:38+00:00"
          },
          "creator_id": {
            "description": "The ID of the user who created the client",
            "type": "integer",
            "example": 2166261
          },
          "integration_ext_id": {
            "description": "The external ID of the linked entity in the external system (e.g. JIRA/SalesForce)",
            "type": "string"
          },
          "integration_ext_type": {
            "description": "The external type of the linked entity in the external system (e.g. JIRA/SalesForce)",
            "type": "string"
          },
          "integration_provider": {
            "description": "The provider (e.g. JIRA/SalesForce) that has an entity linked to this Toggl Track entity",
            "type": "string"
          },
          "notes": {
            "type": "string"
          },
          "permissions": {
            "description": "List of authorization permissions for this client.",
            "type": "string"
          }
        },
        "required": [
          "id",
          "wid",
          "archived",
          "name",
          "at",
          "creator_id"
        ],
        "example": {
          "id": 64890399,
          "wid": 2230580,
          "archived": false,
          "name": "AGL",
          "at": "2024-03-17T10:55:38+00:00",
          "creator_id": 2166261
        }
      },
      "TimeEntries": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/TimeEntry"
        }
      },
      "TimeEntry": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 3727977106
          },
          "workspace_id": {
            "type": "integer",
            "example": 2230580
          },
          "project_id": {
            "type": "integer",
            "example": 155392684
          },
          "task_id": {
            "type": "object"
          },
          "billable": {
            "type": "boolean",
            "example": false
          },
          "start": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-13T00:18:26+00:00"
          },
          "stop": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-12T20:38:05+00:00"
          },
          "duration": {
            "type": "integer",
            "example": -1734035934
          },
          "description": {
            "type": "string",
            "example": "Open Sourcing"
          },
          "tags": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "tag_ids": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "duronly": {
            "type": "boolean",
            "example": true
          },
          "at": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-12T20:40:28.056447Z"
          },
          "server_deleted_at": {
            "type": "object"
          },
          "user_id": {
            "type": "integer",
            "example": 2166261
          },
          "uid": {
            "type": "integer",
            "example": 2166261
          },
          "wid": {
            "type": "integer",
            "example": 2230580
          },
          "pid": {
            "type": "integer",
            "example": 155392684
          }
        },
        "required": [
          "id",
          "workspace_id",
          "project_id",
          "task_id",
          "billable",
          "start",
          "stop",
          "duration",
          "description",
          "tags",
          "tag_ids",
          "duronly",
          "at",
          "server_deleted_at",
          "user_id",
          "uid",
          "wid",
          "pid"
        ],
        "example": {
          "id": 3727977106,
          "workspace_id": 2230580,
          "project_id": 155392684,
          "task_id": null,
          "billable": false,
          "start": "2024-12-13T00:18:26+00:00",
          "stop": null,
          "duration": -1734049107,
          "description": "Open Sourcing",
          "tags": [],
          "tag_ids": [],
          "duronly": true,
          "at": "2024-12-13T00:18:26.835197Z",
          "server_deleted_at": null,
          "user_id": 2166261,
          "uid": 2166261,
          "wid": 2230580,
          "pid": 155392684
        }
      },
      "Options": {
        "type": "object",
        "additionalProperties": {
          "type": "string"
        }
      },
      "Projects": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Project"
        }
      },
      "Project": {
        "type": "object",
        "properties": {
          "id": {
            "description": "Project ID",
            "type": "integer",
            "example": 63334144
          },
          "workspace_id": {
            "type": "integer",
            "example": 2230580
          },
          "client_id": {
            "description": "Client ID",
            "type": "integer",
            "example": 64890399,
            "x-nullable": true
          },
          "name": {
            "type": "string",
            "example": "AGL Academy (Course Creation & Improvement)"
          },
          "is_private": {
            "type": "boolean",
            "example": false
          },
          "active": {
            "description": "Whether the project is active or archived",
            "type": "boolean",
            "example": true
          },
          "at": {
            "description": "Last updated date",
            "type": "string",
            "format": "date-time",
            "example": "2024-03-17T10:58:40+00:00"
          },
          "created_at": {
            "description": "Creation date",
            "type": "string",
            "format": "date-time",
            "example": "2017-08-28T10:47:38+00:00"
          },
          "server_deleted_at": {
            "type": "object"
          },
          "color": {
            "description": "Color",
            "type": "string",
            "example": "#0b83d9"
          },
          "billable": {
            "description": "Whether the project is billable, premium feature",
            "type": "boolean",
            "example": false,
            "x-nullable": true
          },
          "template": {
            "type": "object"
          },
          "auto_estimates": {
            "description": "Whether estimates are based on task hours, premium feature",
            "type": "boolean",
            "x-nullable": true
          },
          "current_period": {
            "$ref": "#/components/schemas/RecurringPeriod"
          },
          "end_date": {
            "description": "End date",
            "type": "string"
          },
          "estimated_hours": {
            "description": "Estimated hours",
            "type": "integer",
            "x-nullable": true
          },
          "estimated_seconds": {
            "description": "Estimated seconds",
            "type": "integer",
            "x-nullable": true
          },
          "rate": {
            "type": "object"
          },
          "rate_last_updated": {
            "type": "object"
          },
          "currency": {
            "description": "Currency, premium feature",
            "type": "string",
            "x-nullable": true
          },
          "recurring": {
            "type": "boolean",
            "example": false
          },
          "template_id": {
            "type": "object"
          },
          "recurring_parameters": {
            "type": "object"
          },
          "fixed_fee": {
            "description": "Fixed fee, premium feature",
            "type": "number"
          },
          "actual_hours": {
            "description": "Actual hours",
            "type": "integer",
            "example": 1103,
            "x-nullable": true
          },
          "actual_seconds": {
            "description": "Actual seconds",
            "type": "integer",
            "example": 3973324,
            "x-nullable": true
          },
          "tasks_count": {
            "type": "object"
          },
          "can_track_time": {
            "type": "boolean",
            "example": false
          },
          "start_date": {
            "type": "string",
            "example": "2017-08-28"
          },
          "status": {
            "type": "string",
            "example": "active"
          },
          "wid": {
            "type": "integer",
            "example": 2230580
          },
          "cid": {
            "description": "Client ID legacy field",
            "type": "integer",
            "example": 64890399
          },
          "is_shared": {
            "type": "boolean",
            "example": false
          },
          "pinned": {
            "type": "boolean",
            "example": false
          },
          "integration_ext_id": {
            "description": "The external ID of the linked entity in the external system (e.g. JIRA/SalesForce)",
            "type": "string"
          },
          "integration_ext_type": {
            "description": "The external type of the linked entity in the external system (e.g. JIRA/SalesForce)",
            "type": "string"
          },
          "integration_provider": {
            "description": "The provider (e.g. JIRA/SalesForce) that has an entity linked to this Toggl Track entity",
            "type": "string"
          }
        },
        "required": [
          "id",
          "workspace_id",
          "client_id",
          "name",
          "is_private",
          "active",
          "at",
          "created_at",
          "server_deleted_at",
          "color",
          "billable",
          "template",
          "auto_estimates",
          "estimated_hours",
          "estimated_seconds",
          "rate",
          "rate_last_updated",
          "currency",
          "recurring",
          "template_id",
          "recurring_parameters",
          "fixed_fee",
          "actual_hours",
          "actual_seconds",
          "tasks_count",
          "can_track_time",
          "start_date",
          "status",
          "wid",
          "cid",
          "is_shared",
          "pinned"
        ],
        "example": {
          "id": 63334144,
          "workspace_id": 2230580,
          "client_id": 64890399,
          "name": "AGL Academy (Course Creation & Improvement)",
          "is_private": false,
          "active": true,
          "at": "2024-03-17T10:58:40+00:00",
          "created_at": "2017-08-28T10:47:38+00:00",
          "server_deleted_at": null,
          "color": "#0b83d9",
          "billable": false,
          "template": null,
          "auto_estimates": null,
          "estimated_hours": null,
          "estimated_seconds": null,
          "rate": null,
          "rate_last_updated": null,
          "currency": null,
          "recurring": false,
          "template_id": null,
          "recurring_parameters": null,
          "fixed_fee": null,
          "actual_hours": 1103,
          "actual_seconds": 3973324,
          "tasks_count": null,
          "can_track_time": false,
          "start_date": "2017-08-28",
          "status": "active",
          "wid": 2230580,
          "cid": 64890399,
          "is_shared": false,
          "pinned": false
        }
      },
      "Workspaces": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Workspace"
        }
      },
      "Workspace": {
        "type": "object",
        "properties": {
          "id": {
            "type": "integer",
            "example": 2230580
          },
          "organization_id": {
            "type": "integer",
            "example": 2108099
          },
          "name": {
            "type": "string",
            "example": "Atlantean Renaissance"
          },
          "premium": {
            "type": "boolean",
            "example": false
          },
          "business_ws": {
            "type": "boolean",
            "example": false
          },
          "admin": {
            "type": "boolean",
            "example": true
          },
          "role": {
            "type": "string",
            "example": "admin"
          },
          "suspended_at": {
            "type": "object"
          },
          "server_deleted_at": {
            "type": "object"
          },
          "default_hourly_rate": {
            "type": "object"
          },
          "rate_last_updated": {
            "type": "object"
          },
          "default_currency": {
            "type": "string",
            "example": "USD"
          },
          "only_admins_may_create_projects": {
            "type": "boolean",
            "example": false
          },
          "only_admins_may_create_tags": {
            "type": "boolean",
            "example": false
          },
          "only_admins_see_billable_rates": {
            "type": "boolean",
            "example": false
          },
          "only_admins_see_team_dashboard": {
            "type": "boolean",
            "example": false
          },
          "projects_billable_by_default": {
            "type": "boolean",
            "example": true
          },
          "projects_private_by_default": {
            "type": "boolean",
            "example": true
          },
          "projects_enforce_billable": {
            "type": "boolean",
            "example": false
          },
          "limit_public_project_data": {
            "type": "boolean",
            "example": false
          },
          "last_modified": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-12T00:00:00Z"
          },
          "reports_collapse": {
            "type": "boolean",
            "example": true
          },
          "rounding": {
            "type": "integer",
            "example": 0
          },
          "rounding_minutes": {
            "type": "integer",
            "example": 0
          },
          "api_token": {
            "type": "string",
            "format": "uuid",
            "example": "831d9ff9f4bdebc4b33aeec85526a300"
          },
          "at": {
            "type": "string",
            "format": "date-time",
            "example": "2024-12-12T11:00:55+00:00"
          },
          "logo_url": {
            "type": "string",
            "format": "uri",
            "example": "https://assets.track.toggl.com/images/workspace.jpg"
          },
          "ical_url": {
            "type": "string",
            "example": "/ical/workspace_user/4cbf3bdb29573494d335bee61b2c12a7"
          },
          "ical_enabled": {
            "type": "boolean",
            "example": true
          },
          "csv_upload": {
            "type": "object"
          },
          "subscription": {
            "type": "object"
          },
          "hide_start_end_times": {
            "type": "boolean",
            "example": false
          },
          "working_hours_in_minutes": {
            "type": "object"
          }
        },
        "required": [
          "id",
          "organization_id",
          "name",
          "premium",
          "business_ws",
          "admin",
          "role",
          "suspended_at",
          "server_deleted_at",
          "default_hourly_rate",
          "rate_last_updated",
          "default_currency",
          "only_admins_may_create_projects",
          "only_admins_may_create_tags",
          "only_admins_see_billable_rates",
          "only_admins_see_team_dashboard",
          "projects_billable_by_default",
          "projects_private_by_default",
          "projects_enforce_billable",
          "limit_public_project_data",
          "last_modified",
          "reports_collapse",
          "rounding",
          "rounding_minutes",
          "api_token",
          "at",
          "logo_url",
          "ical_url",
          "ical_enabled",
          "csv_upload",
          "subscription",
          "hide_start_end_times",
          "working_hours_in_minutes"
        ],
        "example": {
          "id": 2230580,
          "organization_id": 2108099,
          "name": "Atlantean Renaissance",
          "premium": false,
          "business_ws": false,
          "admin": true,
          "role": "admin",
          "suspended_at": null,
          "server_deleted_at": null,
          "default_hourly_rate": null,
          "rate_last_updated": null,
          "default_currency": "USD",
          "only_admins_may_create_projects": false,
          "only_admins_may_create_tags": false,
          "only_admins_see_billable_rates": false,
          "only_admins_see_team_dashboard": false,
          "projects_billable_by_default": true,
          "projects_private_by_default": true,
          "projects_enforce_billable": false,
          "limit_public_project_data": false,
          "last_modified": "2024-12-12T00:00:00Z",
          "reports_collapse": true,
          "rounding": 0,
          "rounding_minutes": 0,
          "api_token": "831d9ff9f4bdebc4b33aeec85526a300",
          "at": "2024-12-12T11:00:55+00:00",
          "logo_url": "https://assets.track.toggl.com/images/workspace.jpg",
          "ical_url": "/ical/workspace_user/4cbf3bdb29573494d335bee61b2c12a7",
          "ical_enabled": true,
          "csv_upload": null,
          "subscription": null,
          "hide_start_end_times": false,
          "working_hours_in_minutes": null
        }
      },
      "RecurringPeriod": {
        "type": "object"
      },
      "PostWorkspaces2230580TimeEntriesBadRequestJSONResponse": {
        "type": "string",
        "example": "Start time year must be between 2006 and 2030"
      },
      "NewTimeEntry": {
        "type": "object",
        "properties": {
          "billable": {
            "description": "Whether the time entry is marked as billable, optional, default false",
            "type": "boolean",
            "example": false
          },
          "created_with": {
            "description": "Must be provided when creating a time entry and should identify the service/application used to create it",
            "type": "string",
            "example": "API example code"
          },
          "description": {
            "description": "Time entry description, optional",
            "type": "string",
            "example": "Hello Toggl"
          },
          "duration": {
            "description": "Time entry duration. For running entries should be negative, preferable -1",
            "type": "integer"
          },
          "duronly": {
            "description": "Deprecated: Used to create a time entry with a duration but without a stop time. This parameter can be ignored.",
            "type": "boolean"
          },
          "event_metadata": {
            "$ref": "#/components/schemas/EventMetadata"
          },
          "pid": {
            "description": "Project ID, legacy field",
            "type": "integer"
          },
          "project_id": {
            "description": "Project ID, optional",
            "type": "integer"
          },
          "shared_with_user_ids": {
            "description": "List of user IDs to share this time entry with",
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "start": {
            "description": "Start time, required for creation.",
            "type": "string",
            "format": "date-time",
            "example": "1984-06-08T11:02:53.000Z"
          },
          "start_date": {
            "description": "If provided during creation, the date part will take precedence over the date part of \"start\". Format: 2006-11-07",
            "type": "string"
          },
          "stop": {
            "description": "Stop time in UTC, can be omitted if it's still running or created with \"duration\".\nIf \"stop\" and \"duration\" are provided, values must be consistent (start + duration == stop)",
            "type": "string"
          },
          "tag_action": {
            "$ref": "#/components/schemas/TagAction"
          },
          "tag_ids": {
            "description": "IDs of tags to add/remove",
            "type": "array",
            "items": {
              "type": "integer"
            }
          },
          "tags": {
            "description": "Names of tags to add/remove. If name does not exist as tag, one will be created automatically",
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "task_id": {
            "description": "Task ID, optional",
            "type": "integer"
          },
          "tid": {
            "description": "Task ID, legacy field",
            "type": "integer"
          },
          "uid": {
            "description": "Time Entry creator ID, legacy field",
            "type": "integer"
          },
          "user_id": {
            "description": "Time Entry creator ID, if omitted will use the requester user ID",
            "type": "integer"
          },
          "wid": {
            "description": "Workspace ID, legacy field",
            "type": "integer"
          },
          "workspace_id": {
            "description": "Workspace ID",
            "type": "integer",
            "example": 2230580
          }
        },
        "required": [
          "created_with",
          "description",
          "tags",
          "billable",
          "workspace_id",
          "start"
        ],
        "example": {
          "created_with": "API example code",
          "description": "Hello Toggl",
          "tags": [],
          "billable": false,
          "workspace_id": 2230580,
          "start": "1984-06-08T11:02:53.000Z"
        }
      },
      "EventMetadata": {
        "type": "object"
      },
      "TagAction": {
        "description": "Used when updating an existing time entry",
        "type": "string",
        "enum": [
          "add",
          "delete"
        ]
      }
    },
    "responses": {
      "UnauthorizedResponse": {
        "description": "User is unauthorized to use the API"
      },
      "UserResponse": {
        "description": "Returns the user.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/UserWithRelated"
            },
            "example": {
              "id": 2166261,
              "api_token": "********************************",
              "email": "marcodroesler@gmail.com",
              "fullname": "Marco",
              "timezone": "Europe/Berlin",
              "toggl_accounts_id": "WSBrE7LiQPJ7PKA7WnCAnk",
              "default_workspace_id": 2230580,
              "beginning_of_week": 1,
              "image_url": "https://secure.gravatar.com/avatar/af0a4ad100669ddbc678eb40ba90459d?d=404&s=200",
              "created_at": "2016-03-20T20:40:08.017845Z",
              "updated_at": "2024-11-26T17:13:54.850204Z",
              "openid_email": null,
              "openid_enabled": true,
              "country_id": null,
              "has_password": true,
              "at": "2024-12-11T17:43:57.206072Z",
              "intercom_hash": "ea08fc8166eed37e79f7179c3c8334cd99ae5afbbd0339ab1ecb333fb1615d52",
              "oauth_providers": [
                "google"
              ],
              "authorization_updated_at": "2024-07-02T14:55:08.008327Z"
            }
          }
        }
      },
      "TimeEntryResponse": {
        "description": "Returns a time entry",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/TimeEntry"
            },
            "example": {
              "id": 3727977106,
              "workspace_id": 2230580,
              "project_id": 155392684,
              "task_id": null,
              "billable": false,
              "start": "2024-12-13T00:18:26+00:00",
              "stop": null,
              "duration": -1734049107,
              "description": "Open Sourcing",
              "tags": [],
              "tag_ids": [],
              "duronly": true,
              "at": "2024-12-13T00:18:26.835197Z",
              "server_deleted_at": null,
              "user_id": 2166261,
              "uid": 2166261,
              "wid": 2230580,
              "pid": 155392684
            }
          }
        }
      },
      "PostWorkspaces2230580TimeEntriesBadRequestResponse": {
        "description": "TODO",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/PostWorkspaces2230580TimeEntriesBadRequestJSONResponse"
            },
            "example": "Start time year must be between 2006 and 2030"
          }
        }
      }
    },
    "parameters": {
      "with_related_data": {
        "name": "with_related_data",
        "in": "query",
        "description": "Retrieve user related data (clients, projects, tasks, tags, workspaces, time entries, etc.)",
        "schema": {
          "type": "boolean",
          "example": true
        },
        "example": true
      },
      "workspace_id": {
        "name": "workspace_id",
        "in": "path",
        "description": "Numeric ID of the workspace",
        "required": true,
        "schema": {
          "type": "integer",
          "example": 2230580
        }
      }
    },
    "requestBodies": {
      "TimeEntry": {
        "required": true,
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/NewTimeEntry"
            },
            "example": {
              "created_with": "API example code",
              "description": "Hello Toggl",
              "tags": [],
              "billable": false,
              "workspace_id": 2230580,
              "start": "1984-06-08T11:02:53.000Z"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "BasicAuth": {
        "type": "http",
        "description": "The Authorization header is constructed either using the email and password or the API token and the string literal 'api_token'.",
        "scheme": "basic"
      }
    }
  },
  "security": [
    {
      "BasicAuth": []
    }
  ]
}